### ISSUE TITLE
compound transforms loose attributes

### ISSUE THREAD

**Issue by nden** [spacetelescope/pyasdf#87]
This only happens with compound transforms. Attributes like `name` and `inverse` are lost.
```
offx = models.Shift(1)
scl = models.Scale(2)
model = (offx | scl).rename('compound_model')
f = AsdfFile()
f.tree['model'] = model
f.write_to('test.asdf')
f1 = AsdfFile.read('test.asdf')
f1.tree['model'].name
model.name
Out[97]: 'compound_model'
```

**Comment by mdboom** [comment]
Thanks, @nden.  I'm on it...

**Comment by embray** [comment]
For inverse would that have anything to do with astropy/astropy#3542, or is this purely a serialization issue?

(For the record, that issue turned out to be not easy to fix, but I need to rework the data structure used for compound models a bit.  For what it's worth I don't think that will result in too much chaos for pyasdf, but I'll test my changes side-by-side...)

**Comment by nden** [comment]
This is a serialization issue only.

**Comment by nden** [comment]
I should mention though that although this will fix the serialization issue the inverse still can't be used until  the other issue is fixed in astropy.
